### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by ch1998** [zju3dv/mlp_maps#15]
Great work, I tried to run the given demo, sport1.
Run the command python run.py --config configs/nhr/sport1.py mode evaluate fast_render True
The following error occurs：
Traceback (most recent call last):
  File "run.py", line 122, in <module>
    globals()['run_' + cfg.mode]()
  File "run.py", line 74, in run_evaluate
    output = renderer.render(batch)
  File "lib/networks/renderer/dymap_fast_renderer.py", line 306, in render
    self.render_chunk(ray_o_chunk, ray_d_chunk, batch)            
  File "lib/networks/renderer/dymap_fast_renderer.py", line 246, in render_chunk
    packed_info, t_starts, t_ends = nerfacc.ray_marching(
  File "/mnt/data/local-disk2/software/anaconda3/envs/mlp_maps/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/local-disk2/ch2/Nerf/mlp_maps-master/lib/csrc/nerfacc/ray_marching.py", line 141, in ray_marching
    t_min, t_max = ray_aabb_intersect(rays_o, rays_d, scene_aabb)
  File "/mnt/data/local-disk2/software/anaconda3/envs/mlp_maps/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/local-disk2/ch2/Nerf/mlp_maps-master/lib/csrc/nerfacc/intersection.py", line 47, in ray_aabb_intersect
    t_min, t_max = _C.ray_aabb_intersect(rays_o, rays_d, aabb)
  File "/mnt/data/local-disk2/ch2/Nerf/mlp_maps-master/lib/csrc/nerfacc/cuda/__init__.py", line 11, in call_cuda
    from ._backend import _C
  File "/mnt/data/local-disk2/ch2/Nerf/mlp_maps-master/lib/csrc/nerfacc/cuda/_backend.py", line 39, in <module>
    _C = load_extention(name)
  File "/mnt/data/local-disk2/ch2/Nerf/mlp_maps-master/lib/csrc/nerfacc/cuda/_backend.py", line 26, in load_extention
    return load(
  File "/mnt/data/local-disk2/software/anaconda3/envs/mlp_maps/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "/mnt/data/local-disk2/software/anaconda3/envs/mlp_maps/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1450, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/mnt/data/local-disk2/software/anaconda3/envs/mlp_maps/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1844, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /home/ch2/.cache/torch_extensions/py38_cu113/nerfacc_cuda/nerfacc_cuda.so: cannot open shared object file: No such file or directory

how should i solve this problem？

**Comment by pengsida** [comment]
It seems that the environment is not set up correctly.

**Comment by ch1998** [comment]
Is it related to kilonerf-cuda?
I installed using option A, but didn't run Finally compile KiloNeRF's C++/CUDA code

**Comment by pengsida** [comment]
No. It is related to Nerfacc.

**Comment by ch1998** [comment]
I will try to install Nerfacc.
There is also this problem in the environment_hash_encoder/_hash_encoder.so：No such file or directory

**Comment by pengsida** [comment]
The Nerfacc and Instant-NGP should be compiled during the running time. It is strange to encounter this problem.

**Comment by ch1998** [comment]
in torch_extensions/py38_cu113/nerfacc_cuda/
drwxrwxr-x 2 ch2 ch2 4096  7月 12 11:30 ./
drwxrwxr-x 6 ch2 ch2 4096  7月 12 11:21 ../
-rw-rw-r-- 1 ch2 ch2 3648  7月 12 11:30 build.ninja

This may not be able to compile successfully, I can't find a solution in the KAIR-BAIR/nerfacc project

**Comment by pengsida** [comment]
You need to find the error message.

**Comment by yunzhiy** [comment]
> in torch_extensions/py38_cu113/nerfacc_cuda/ drwxrwxr-x 2 ch2 ch2 4096 7月 12 11:30 ./ drwxrwxr-x 6 ch2 ch2 4096 7月 12 11:21 ../ -rw-rw-r-- 1 ch2 ch2 3648 7月 12 11:30 build.ninja
> 
> This may not be able to compile successfully, I can't find a solution in the KAIR-BAIR/nerfacc project

You can try to remove the nerfacc_cuda folder and compile again.

**Comment by ch1998** [comment]
> > in torch_extensions/py38_cu113/nerfacc_cuda/ drwxrwxr-x 2 ch2 ch2 4096 7月 12 11:30 ./ drwxrwxr-x 6 ch2 ch2 4096 7月 12 11:21 ../ -rw-rw-r-- 1 ch2 ch2 3648 7月 12 11:30 build.ninja
> > This may not be able to compile successfully, I can't find a solution in the KAIR-BAIR/nerfacc project
> 
> You can try to remove the nerfacc_cuda folder and compile again.

I've tried this, same result, only a build.ninja file is generated。
Strangely, no compile errors are thrown. An error was thrown when compiling _hash_encoder.so, and it can be compiled normally after modification.

**Comment by ch1998** [comment]
> You need to find the error message.

Can you tell me which version of ninja you are using, I guess it may be a problem with ninja

**Comment by yunzhiy** [comment]
1.11.1

**Comment by ch1998** [comment]
The reason for the error is that the path to call cuda is wrong, and the compilation is successful after export CUDA_HOME=/usr/local/cuda

**Comment by ch1998** [comment]
The reason for the error is that the path to call cuda is wrong, and the compilation is successful after export CUDA_HOME=/usr/local/cuda.
After modifying the path, it can be successfully compiled

**Comment by ch1998** [comment]
Thank you for your reply.
